# Generated by Django 4.2.3 on 2024-01-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_deleted',
        ),
    ]
